[tool.poetry]
name = "ghidra-py"
version = "0.1.0"
description = "python port of ghidra"
authors = ["Josh Madden <cyrex562@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
